name = "mtrade"
main = "src/index.ts"
compatibility_date = "2026-03-25"

routes = [
  { pattern = "mtrade.lrxradar.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "mtrade-db"
database_id = "54ffc831-f9ff-4d24-bfbf-1b6f8f580261"
migrations_dir = "migrations"

[triggers]
crons = ["*/1 * * * *"]
